openapi: 3.0.1
info:
  title: Ambulance Invoices Integration Trigger
  x-ibm-name: finance-accounting-api-invoices-ingestion
  version: 2.2.0
  description: |
    **Finance & Accounting API: Invoice Integration Trigger**

    This API facilitates file-based integration workflows between external systems and SAP for finance and accounting purposes.
 
     ### Documentation
    - [Invoice and Payments Financial Data Flows](https://tcsgroup.atlassian.net/wiki/x/HgvwAg)
    - [API Documentation](https://tcsgroup.atlassian.net/wiki/x/MIAmJ)
    - [Initial API Story](https://tcsgroup.atlassian.net/browse/NIPO-6628)

  contact:
    name: 05_IT_Applications_Solutions
    email: 05_IT_Applications_Solutions@tcs.ch

x-change-log:
  - date: 2025-09-03
    author: HUENI Victor
    from: 1.0.0
    to: 2.0.0
    description: |
      Breaking changes : All the response body changes
      Change the flow from async to sync with a multi items response
      Add example in the response of the ingestion
      Add GET /health operation
    ticket: https://tcsgroup.atlassian.net/browse/NIPO-7290
  - date: 2025-09-22
    author: HUENI Victor
    from: 2.0.0
    to: 2.1.0
    description: |
      Added two new operations:
      - POST /sarge-files-injection-trigger (copy of /asv-files-injection-trigger)
      - POST /sarge-files-purge-trigger (copy of /asv-files-purge-trigger)
    ticket: https://tcsgroup.atlassian.net/browse/NIPO-7289
  - date: 2025-09-25
    author: HUENI Victor
    from: 2.1.0
    to: 2.2.0
    description: |
      Added two new operations:
      - POST /sarvd-files-injection-trigger (copy of /asv-files-injection-trigger)
      - POST /sarvd-files-purge-trigger (copy of /asv-files-purge-trigger)
    ticket: https://tcsgroup.atlassian.net/browse/NIPO-7376

externalDocs:
  description: SP TCS multi-business invoice financial data flows
  url: https://tcsgroup.atlassian.net/wiki/x/HgvwAg
  
servers:
  - url: /finance-accounting/v2/invoice-ingestion
paths:
  /asv-files-injection-trigger:
    post:
      tags:
        - ASV Attrib
      description: Post a notification to start files injection flow
      responses:
        '200':
          description: File ingestion triggered successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
              examples:
                SuccessfulProcessing:
                  $ref: '#/components/examples/SuccessfulProcessing'
                FailedProcessing:
                  $ref: '#/components/examples/FailedProcessing'
                PartialFailureProcessing:
                  $ref: '#/components/examples/PartialFailureProcessing'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '422':
          description: Unprocessable Entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                EmptyProcessing:
                  $ref: '#/components/examples/EmptyProcessing'
                TechnicalIssueOnTheFlow:
                  $ref: '#/components/examples/TechnicalIssueOnTheFlow'
        '502':
          description: Bad Gateway.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '503':
          description: Service Unavailable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
  /asv-files-purge-trigger:
    post:
      tags:
        - ASV Attrib
      description: Post a notification to start files purge flow
      responses:
        '202':
          description: File purge triggered successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurgeResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '501':
          description: Not Implemented.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '502':
          description: Bad Gateway.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '503':
          description: Service Unavailable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
  /sarge-files-injection-trigger:
      post:
        tags:
          - SARGE Attrib
        description: Post a notification to start files injection flow
        responses:
          '200':
            description: File ingestion triggered successfully.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/IngestionResponse'
                examples:
                  SuccessfulProcessing:
                    $ref: '#/components/examples/SuccessfulProcessing'
                  FailedProcessing:
                    $ref: '#/components/examples/FailedProcessing'
                  PartialFailureProcessing:
                    $ref: '#/components/examples/PartialFailureProcessing'
          '400':
            description: Bad Request.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '401':
            description: Unauthorized.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '403':
            description: Forbidden.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '404':
            description: Not Found.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '422':
            description: Unprocessable Entity.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '429':
            description: Too Many Requests.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '500':
            description: Internal Server Error.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
                examples:
                  EmptyProcessing:
                    $ref: '#/components/examples/EmptyProcessing'
                  TechnicalIssueOnTheFlow:
                    $ref: '#/components/examples/TechnicalIssueOnTheFlow'
          '502':
            description: Bad Gateway.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '503':
            description: Service Unavailable.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
  /sarge-files-purge-trigger:
    post:
      tags:
        - SARGE Attrib
      description: Post a notification to start files purge flow
      responses:
        '202':
          description: File ingestion triggered successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurgeResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '501':
          description: Not Implemented.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '502':
          description: Bad Gateway.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '503':
          description: Service Unavailable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'  
  /sarvd-files-injection-trigger:
    post:
        tags:
          - SAR VD Attrib
        description: Post a notification to start files injection flow
        responses:
          '200':
            description: File ingestion triggered successfully.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/IngestionResponse'
                examples:
                  SuccessfulProcessing:
                    $ref: '#/components/examples/SuccessfulProcessing'
                  FailedProcessing:
                    $ref: '#/components/examples/FailedProcessing'
                  PartialFailureProcessing:
                    $ref: '#/components/examples/PartialFailureProcessing'
          '400':
            description: Bad Request.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '401':
            description: Unauthorized.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '403':
            description: Forbidden.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '404':
            description: Not Found.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '422':
            description: Unprocessable Entity.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '429':
            description: Too Many Requests.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '500':
            description: Internal Server Error.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
                examples:
                  EmptyProcessing:
                    $ref: '#/components/examples/EmptyProcessing'
                  TechnicalIssueOnTheFlow:
                    $ref: '#/components/examples/TechnicalIssueOnTheFlow'
          '502':
            description: Bad Gateway.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
          '503':
            description: Service Unavailable.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ServiceError'
  /sarvd-files-purge-trigger:
    post:
      tags:
        - SAR VD Attrib
      description: Post a notification to start files purge flow
      responses:
        '202':
          description: File purge triggered successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurgeResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '501':
          description: Not Implemented.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '502':
          description: Bad Gateway.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '503':
          description: Service Unavailable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
  /sansys-files-injection-trigger:
    post:
      tags:
        - SANSYS Attrib
      description: Post a notification to start files injection flow
      responses:
        '200':
          description: File ingestion triggered successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
              examples:
                SuccessfulProcessing:
                  $ref: '#/components/examples/SuccessfulProcessing'
                FailedProcessing:
                  $ref: '#/components/examples/FailedProcessing'
                PartialFailureProcessing:
                  $ref: '#/components/examples/PartialFailureProcessing'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '422':
          description: Unprocessable Entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                EmptyProcessing:
                  $ref: '#/components/examples/EmptyProcessing'
                TechnicalIssueOnTheFlow:
                  $ref: '#/components/examples/TechnicalIssueOnTheFlow'
        '502':
          description: Bad Gateway.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '503':
          description: Service Unavailable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
  /sansys-files-purge-trigger:
    post:
      tags:
        - SANSYS Attrib
      description: Post a notification to start files purge flow
      responses:
        '202':
          description: File purge triggered successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurgeResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '501':
          description: Not Implemented.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '502':
          description: Bad Gateway.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '503':
          description: Service Unavailable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
  /health:
    get:
      summary: Pings the target receiver to check the connection
      operationId: get-health
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthType'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '501':
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '502':
          description: Bad gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'

components:
  schemas:
    ServiceError:
      title: ServiceError
      type: object
      description: Object returned when errors occurred
      properties:
        httpCode:
          type: string
        httpMessage:
          type: string
        moreInformation:
          type: string
      required:
        - httpCode
        - httpMessage
        - moreInformation

    IngestionResponse:
      title: IngestionResponse
      type: object
      description: Response returned when the ingestion trigger has been evaluated.
      properties:
        meta:
          type: object
          properties:
            submissionId:
              type: string
              example: "4a9a3b64-8a14-4a31-9b47-6f38f4c57a7c"
            timestamp:
              type: string
              format: date-time
              example: "2025-09-25T14:48:00"
          required:
            - submissionId
            - timestamp
        data:
          type: object
          properties:
            status:
              type: string
              example: COMPLETED
            receivedCount:
              type: integer
              example: 3
            message:
              type: string
              example: Batch file ingestion completed.
          required:
            - status
            - receivedCount
            - message
      required:
        - meta
        - data

    PurgeResponse:
      title: PurgeResponse
      type: object
      description: Response returned when the Purge is successfully triggered.
      properties:
        httpCode:
          type: integer
          example: 202
        httpMessage:
          type: string
          example: "Accepted"
        moreInformation:
          type: string
          example: "ASV File Purge triggered properly"
      required:
        - httpCode
        - httpMessage
        - moreInformation
        
    HealthType:
      type: object
      properties:
        status:
          type: string
          description: status of the health check
          enum: [pass, error]
        api:
          type: string
          description: api/app name of the component
        timestamp:
          type: string
          format: date-time
        checks:
          type: array
          items:
            $ref: '#/components/schemas/Check'
    Check:
      type: object
      description: 'describe a component check (MQ, DataBase, BackEnd etc..)'
      properties:
        component:
          type: string
          description: 'name of the tested component (MQ, Baloise, Toni, etc..)'
        status:
          type: string
          description: status of the tested component
          enum: [pass, error, warn]
        details:
          type: string
          description: details

  examples:
    EmptyProcessing:
      summary: No invoices processed
      value:
        httpCode: '500'
        httpMessage: 'Internal server error'
        moreInformation: 'Error reading file. File is missing, file is empty or file is bad formated(JSON)'
    TechnicalIssueOnTheFlow:
      summary: Either ACE app / SAP is having tehcnical issue
      value:
        httpCode: '500'
        httpMessage: 'Internal server error'
        moreInformation: 'Error calling SAP. Invoices moved to error file'
    FailedProcessing:
      summary: Ingestion completed with technical failures
      value:
        meta:
          submissionId: '4a9a3b64-8a14-4a31-9b47-6f38f4c57a7c'
          timestamp: '2025-09-25T14:48:00'
        data:
          status: FAILED
          receivedCount: 2
          message: Invoices moved to error file.
    SuccessfulProcessing:
      summary: Ingestion completed
      value:
        meta:
          submissionId: '4a9a3b64-8a14-4a31-9b47-6f38f4c57a7c'
          timestamp: '2025-09-25T14:48:00'
        data:
          status: COMPLETED
          receivedCount: 2
          message: Batch file ingestion completed.
    PartialFailureProcessing:
      summary: Ingestion completed with warnings
      value:
        meta:
          submissionId: '4a9a3b64-8a14-4a31-9b47-6f38f4c57a7c'
          timestamp: '2025-09-25T14:48:00'
        data:
          status: PARTIAL_SUCCESS
          receivedCount: 5
          message: Batch file ingestion completed with some invoices written to the error folder.